<a href="https://colab.research.google.com/github/kdaughtry/Week4LibraryJuiceAcademy/blob/main/Copy_of_Week_3_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 ### Student Name

Katie Daughtry

## Submitting your homework!

Two steps are required for this week's homework once you have completed it:

- __Share__ this notebook with _libraryjuicepresspython@gmail.com_ so it can be marked in Colab
- __Print as PDF__ and upload to the the week's homework submission location on the Library Juice Academy LMS

# Advanced Python - Week 3 Homework

(Be sure to copy to drive first)

For this homework we are going to apply some text analysis stuff to a collection of PDF file that I'll ask you to put together.

In [ ]:
#Install / load our libraries and connect to Google Drive

!pip install pypdf

#Colab has a special library just for working with files on google drive
from google.colab import drive


#This is a new library we'll use to extract text from PDFs
from pypdf import PdfReader


import textblob
import pandas as pd
import numpy as np
import glob

#Some extra libraries we'll need for text analysis
import nltk
nltk.download('punkt')
nltk.download('brown')
nltk.download('punkt_tab')
nltk.download('stopwords')

from nltk.corpus import stopwords

#Connect to Gdrive
drive.mount('/content/gdrive')

print("Libraries and Drive Ready!")

Requirement already satisfied: pypdf in /usr/local/lib/python3.13/dist-packages (6.21.1)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Package brown is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
Libraries and Drive Ready!

**H1**


Part of the work for this week is going to be finding a collection of 6 or so PDFs. These PDFS ideally should be on the same thing (journal articles on the same topic). Additionally these PDFs whould be Open Access, or the very least obtained lawfully * ***ahem*** *.

Copy these 6 PDFs into the `LibraryJuicePython` folder on Google Drive. We'll be peforming some text analysis on these files.

In [ ]:
#Run this cell to see the files in your directory
for file in glob.glob("/content/gdrive/MyDrive/LibraryJuicePython/*.pdf"):
  print(file)

# Exracting the text from the PDFs

We'll use a Python Library to create a text file of the contents of the PDF file.

In [ ]:

for file in glob.glob("/content/gdrive/MyDrive/LibraryJuicePython/*.pdf"):
  filename = file.split("/")[-1]
  print("Extracting text for... ",filename)

  text = ""
  #This bit is new!
  reader = PdfReader(file)
  for page in reader.pages:
    text += page.extract_text()

  #Output the string variable into a text file
  output_text_file = filename+".txt"
  with open(output_text_file, "w") as text_file:
    text_file.write(text)

Extracting text for...  Vermont, the unspoiled land.pdf
Extracting text for...  A list of desirable farms and summer homes in Vermont.pdf
Extracting text for...  Vermont, the land of Green Mountains..pdf
Extracting text for...  Vermont, a souvenir of its government, 1902-1903.pdf
Extracting text for...  Vermont broadsides.pdf
Extracting text for...  Geography and geology of Vermont.pdf

# Sentiment of our PDFs

Let's just print our sentiment scores to the screen for now.

In [ ]:
for file in glob.glob("*.txt"):
  print("Sentiment for ",file)
  with open(file,"r") as text_file:
    text = text_file.read()
    blob = textblob.TextBlob(text)
    print(blob.sentiment)
    print("---")

Sentiment for  Geography and geology of Vermont.pdf.txt
Sentiment(polarity=0.11787409772828568, subjectivity=0.3954524184367121)
---
Sentiment for  Vermont, the unspoiled land.pdf.txt
Sentiment(polarity=0.14779496820676702, subjectivity=0.4339600991557775)
---
Sentiment for  A list of desirable farms and summer homes in Vermont.pdf.txt
Sentiment(polarity=0.25984158805329627, subjectivity=0.4935968690943373)
---
Sentiment for  Vermont, a souvenir of its government, 1902-1903.pdf.txt
Sentiment(polarity=0.021538963622669945, subjectivity=0.36201618758243653)
---
Sentiment for  Vermont broadsides.pdf.txt
Sentiment(polarity=0.15880874289151775, subjectivity=0.46747485380419185)
---
Sentiment for  Vermont, the land of Green Mountains..pdf.txt
Sentiment(polarity=0.138756299045228, subjectivity=0.4071833106795065)
---

# Noun Phrases of our PDFs

We'll just do the top 3 keywords of each file and display it to the screen. Be sure to add some extra stopwords to filter out things that are not helping your understand the contents of your files.

Simply add some more strings to the `extra_words` list variable that begins on line `1`. You can re-run the cell below as you experiment with more stopwords removed. I've include some extra stopwords already that were useful for me.

In [ ]:
extra_words = [
    "’ s",
    "’ ve",
    "’ m",
    "vermont"
]

sw = stopwords.words('english')

for word in extra_words:
  sw.append(word)

for file in glob.glob("*.txt"):
  print("Top 5 Phrases for ",file)
  with open(file,"r") as text_file:
    text = text_file.read()

  blob = textblob.TextBlob(text)
  nphrases = dict()

  for np in blob.noun_phrases:
    if np not in sw:
      if np in nphrases:
          nphrases[np] += 1
      else:
          nphrases[np] = 1

  for np in sorted(nphrases, key=nphrases.get, reverse=True)[0:3]:
      print(np, nphrases[np])

  print("---")

Top 5 Phrases for  Geography and geology of Vermont.pdf.txt
champlain 68
square miles 51
burlington 48
---
Top 5 Phrases for  Vermont, the unspoiled land.pdf.txt
woodstock 24
mountain tour 23
johnsbury 19
---
Top 5 Phrases for  A list of desirable farms and summer homes in Vermont.pdf.txt
price 122
address 108
sugar orchard 94
---
Top 5 Phrases for  Vermont, a souvenir of its government, 1902-1903.pdf.txt
religious preference 256
republican 228
common schools 156
---
Top 5 Phrases for  Vermont broadsides.pdf.txt
woodstock 55
age 53
spirit 40
---
Top 5 Phrases for  Vermont, the land of Green Mountains..pdf.txt
champlain 95
york 89
connecticut 87
---


# Dataframe of results

Let's put our findings into a dataframe and save them to our drive. (We will use these PDFs again in our Week 4 work)

In [ ]:

data_set = []

for file in glob.glob("*.txt"):

  pdf_detail = []

  with open(file,"r") as text_file:
    text = text_file.read()
  blob = textblob.TextBlob(text)

  print("working on ",file)
  pdf_detail.append(file)
  pdf_detail.append(blob.sentiment.polarity)
  pdf_detail.append(blob.sentiment.subjectivity)


  nphrases = dict()
  for np in blob.noun_phrases:
    if np not in sw:
      if np in nphrases:
        nphrases[np] += 1
      else:
        nphrases[np] = 1

  #This is a weird way to find the top three keywords
  #This is an example of 'hacky' code

  #we loop through the first entry [0:1] in the sorted keyword list
  #giving us keyword one
  for np in sorted(nphrases, key=nphrases.get, reverse=True)[0:1]:
      keyword_one = np
      pdf_detail.append(keyword_one)

  #we loop through the first entry [1:2] in the sorted keyword list
  #giving us keyword two
  for np in sorted(nphrases, key=nphrases.get, reverse=True)[1:2]:
      keyword_two = np
      pdf_detail.append(keyword_two)

  #we loop through the first entry [2:3] in the sorted keyword list
  #giving us keyword two
  for np in sorted(nphrases, key=nphrases.get, reverse=True)[2:3]:
      keyword_three = np
      pdf_detail.append(keyword_three)

  data_set.append(pdf_detail)
  print(pdf_detail)
  print("---")

working on  Geography and geology of Vermont.pdf.txt
['Geography and geology of Vermont.pdf.txt', 0.11787409772828568, 0.3954524184367121, 'champlain', 'square miles', 'burlington']
---
working on  Vermont, the unspoiled land.pdf.txt
['Vermont, the unspoiled land.pdf.txt', 0.14779496820676702, 0.4339600991557775, 'woodstock', 'mountain tour', 'johnsbury']
---
working on  A list of desirable farms and summer homes in Vermont.pdf.txt
['A list of desirable farms and summer homes in Vermont.pdf.txt', 0.25984158805329627, 0.4935968690943373, 'price', 'address', 'sugar orchard']
---
working on  Vermont, a souvenir of its government, 1902-1903.pdf.txt
['Vermont, a souvenir of its government, 1902-1903.pdf.txt', 0.021538963622669945, 0.36201618758243653, 'religious preference', 'republican', 'common schools']
---
working on  Vermont broadsides.pdf.txt
['Vermont broadsides.pdf.txt', 0.15880874289151775, 0.46747485380419185, 'woodstock', 'age', 'spirit']
---
working on  Vermont, the land of Green Mountains..pdf.txt
['Vermont, the land of Green Mountains..pdf.txt', 0.138756299045228, 0.4071833106795065, 'champlain', 'york', 'connecticut']
---

In [ ]:
#We now have a list of lists
#This sorta looks like JSON doesn't it?
data_set

[['Geography and geology of Vermont.pdf.txt',
  0.11787409772828568,
  0.3954524184367121,
  'champlain',
  'square miles',
  'burlington'],
 ['Vermont, the unspoiled land.pdf.txt',
  0.14779496820676702,
  0.4339600991557775,
  'woodstock',
  'mountain tour',
  'johnsbury'],
 ['A list of desirable farms and summer homes in Vermont.pdf.txt',
  0.25984158805329627,
  0.4935968690943373,
  'price',
  'address',
  'sugar orchard'],
 ['Vermont, a souvenir of its government, 1902-1903.pdf.txt',
  0.021538963622669945,
  0.36201618758243653,
  'religious preference',
  'republican',
  'common schools'],
 ['Vermont broadsides.pdf.txt',
  0.15880874289151775,
  0.46747485380419185,
  'woodstock',
  'age',
  'spirit'],
 ['Vermont, the land of Green Mountains..pdf.txt',
  0.138756299045228,
  0.4071833106795065,
  'champlain',
  'york',
  'connecticut']]

In [ ]:
#Let's turn this list of lists into a pandas dataframe
pdf_dataframe = pd.DataFrame(data_set)
pdf_dataframe

,0,1,2,3,4,5
0,Geography and geology of Vermont.pdf.txt,0.117874,0.395452,champlain,square miles,burlington
1,"Vermont, the unspoiled land.pdf.txt",0.147795,0.433960,woodstock,mountain tour,johnsbury
2,A list of desirable farms and summer homes in ...,0.259842,0.493597,price,address,sugar orchard
3,"Vermont, a souvenir of its government, 1902-19...",0.021539,0.362016,religious preference,republican,common schools
4,Vermont broadsides.pdf.txt,0.158809,0.467475,woodstock,age,spirit
5,"Vermont, the land of Green Mountains..pdf.txt",0.138756,0.407183,champlain,york,connecticut

**H2**

Our dataframe needs better column names. Put the appropriate values into the list below on line 1 to update the column names.

In [ ]:
column_names = ["Title","Polarity","Subjectivity","Top phrase 1","Top phrase 2","Top phrase 3"]
pdf_dataframe.columns = column_names
pdf_dataframe

,Title,Polarity,Subjectivity,Top phrase 1,Top phrase 2,Top phrase 3
0,Geography and geology of Vermont.pdf.txt,0.117874,0.395452,champlain,square miles,burlington
1,"Vermont, the unspoiled land.pdf.txt",0.147795,0.433960,woodstock,mountain tour,johnsbury
2,A list of desirable farms and summer homes in ...,0.259842,0.493597,price,address,sugar orchard
3,"Vermont, a souvenir of its government, 1902-19...",0.021539,0.362016,religious preference,republican,common schools
4,Vermont broadsides.pdf.txt,0.158809,0.467475,woodstock,age,spirit
5,"Vermont, the land of Green Mountains..pdf.txt",0.138756,0.407183,champlain,york,connecticut

# Save our data

We'll save our dataframe as a CSV file and put it in our usual folder.

In [ ]:
pdf_dataframe.to_csv("adv_week3_homework.csv", index=False)
!cp adv_week3_homework.csv /content/gdrive/MyDrive/LibraryJuicePython

**H3** Take a moment to reflect on what your data analysis says about your PDF files. Jot down some reflections in the cell below.

My analysis tells me the books include information on cities in vermont inlcluding Woodstock, Burlington, and Johnsbury, as well as mention of Lake Champlain. It also contains information about local businesses, schools, and local populations.


# All Done!

Congrats you are finished with this week's work. Don't forget to click the `Share` button above and enter `libraryjuicepresspython@gmail.com` so I can get a shared copy of your work. Save this as a PDF and upload it to the Library Juice Academy site.